import os
import sys
import shutil
import time
import json
from concurrent.futures import ThreadPoolExecutor

from fastapi import APIRouter, Body, File, Form, HTTPException, Query, Request, Response
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, PlainTextResponse, StreamingResponse
import httpx

import models
import fastapi_util as futil
import time_util as tutil
import sys_util as sutil
import process_util as putil
from log_util import logger, remove_color_of_shell_text


router = APIRouter()
# _thread_executor: ThreadPoolExecutor|None = None
# HTTP request API configuration: whether to block local/private IP addresses (default False, allow local IP access)
HTTP_REQUEST_BLOCK_LOCAL_IP = False


# def get_thread_executor() -> ThreadPoolExecutor:
#     global _thread_executor
#     if _thread_executor is None:
#         _thread_executor = ThreadPoolExecutor(max_workers=1)
#     return _thread_executor


@router.get("/health")
async def health() -> Response:
    """Health check."""
    return Response(status_code=200)

@router.get("/version", summary='Get version information', description='Get version information')
async def handle_version(request: Request):
    import version

    return {
        'git_data': version.GitDate,
        'git_hash': version.GitCommit,
    }

@router.get("/status", summary='Get server status', description='Get server status information')
async def handle_status(request: Request):
    import serverinfo # serverinfo.py is dynamically generated by docker_monitor_server.py when the server starts

    status = {
        'start_time': serverinfo.StartTime,
        'pid': os.getpid(),
    }
    return status


@router.post("/api/request", response_model=models.ResponseModel,
             summary='Generic HTTP request API',
             description='''Make arbitrary HTTP requests through backend,
support GET, POST and other methods, support custom headers and payload''')
async def make_http_request(request: Request, req_data: models.HttpRequestModel = Body(...)):
    """Generic HTTP request API, allows frontend to make HTTP requests through backend

    Security restrictions (controlled by HTTP_REQUEST_BLOCK_LOCAL_IP variable):
    - Local/private IP address access control (127.0.0.1, localhost, 10.x.x.x, 172.16-31.x.x, 192.168.x.x)
      - Default allows local IP access (HTTP_REQUEST_BLOCK_LOCAL_IP=False)
      - Set to True to block local/private addresses
    - Request timeout limit: default 30 seconds, configurable via `timeout` field
    - All requests are logged

    Args:
        request: FastAPI Request object
        req_data: HTTP request parameters, including method, url, headers, payload

    Returns:
        Dictionary containing status code, response content, and response headers
    """
    import ipaddress
    from urllib.parse import urlparse

    try:
        method = req_data.method.upper()
        url = req_data.url.strip()
        headers = req_data.headers or {}
        payload = req_data.payload
        timeout = float(req_data.timeout) if req_data.timeout is not None else 30.0

        # Log request information
        client_ip = request.client.host if request.client else 'unknown'
        logger.info(f'HTTP request from {client_ip}: method={method}, url={url}')

        # Validate HTTP method
        allowed_methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS']
        if method not in allowed_methods:
            logger.warning(f'Unsupported HTTP method from {client_ip}: {method}')
            return {
                'code': 1,
                'message': f'Unsupported HTTP method: {method}, supported methods: {", ".join(allowed_methods)}',
                'data': None
            }

        # Parse URL
        try:
            parsed_url = urlparse(url)
        except Exception as ex:
            logger.warning(f'Invalid URL format from {client_ip}: {url} - {ex!r}')
            return {
                'code': 2,
                'message': f'Invalid URL format: {ex!r}',
                'data': None
            }

        # Security validation: check hostname
        hostname = parsed_url.hostname
        if not hostname:
            logger.warning(f'URL missing hostname from {client_ip}: {url}')
            return {
                'code': 3,
                'message': 'URL missing hostname',
                'data': None
            }

        # Security validation: block local/private addresses if configured
        if HTTP_REQUEST_BLOCK_LOCAL_IP:
            # Check if it's a local/private address or localhost
            is_local = False
            try:
                # Try to parse as IP address
                ip = ipaddress.ip_address(hostname)
                # Check if it's a private IP or loopback address
                if ip.is_private or ip.is_loopback:
                    is_local = True
            except ValueError:
                # Not an IP address, check if it's a localhost-related domain name
                localhost_names = ['localhost', '127.0.0.1', '0.0.0.0', '::1']
                if hostname.lower() in localhost_names:
                    is_local = True
                # Check if it's an internal domain (.local, .internal, etc.)
                elif any(hostname.lower().endswith(suffix) for suffix in ['.local', '.internal', '.lan']):
                    is_local = True

            if is_local:
                logger.warning(f'SECURITY ALERT: Blocked request to local/private address: {url} from {client_ip}')
                return {
                    'code': 4,
                    'message': 'Access to local/private addresses or localhost is blocked for security reasons',
                    'data': None
                }

            # Log a warning for proxy usage (even if not local)
            logger.info(f'Generic HTTP proxying request: {method} {url} from {client_ip}')

        # Validate protocol (only allow HTTP and HTTPS)
        if parsed_url.scheme not in ['http', 'https']:
            logger.warning(f'Unsupported protocol from {client_ip}: {url} (scheme={parsed_url.scheme})')
            return {
                'code': 5,
                'message': f'Unsupported protocol: {parsed_url.scheme}, only http and https are supported',
                'data': None
            }

        # Prepare request parameters
        request_kwargs = {
            'timeout': timeout,
            'follow_redirects': True,  # Follow redirects
        }

        # Set request headers
        if headers:
            request_kwargs['headers'] = headers

        # Set request body
        if payload is not None:
            if method in ['GET', 'HEAD', 'OPTIONS']:
                logger.warning(f'Method {method} should not have payload, ignoring it')
            else:
                # If payload is dict or list, convert to JSON
                if isinstance(payload, (dict, list)):
                    import json as json_module
                    request_kwargs['json'] = payload
                    # Ensure Content-Type is application/json
                    if 'Content-Type' not in request_kwargs.get('headers', {}):
                        if 'headers' not in request_kwargs:
                            request_kwargs['headers'] = {}
                        request_kwargs['headers']['Content-Type'] = 'application/json'
                else:
                    # String type payload
                    request_kwargs['content'] = str(payload)

        # Make HTTP request
        try:
            async with httpx.AsyncClient() as client:
                # Call corresponding method function
                http_method = getattr(client, method.lower())
                response = await http_method(url, **request_kwargs)

                # Get response content
                try:
                    # Try to get text content
                    response_text = response.text
                except Exception:
                    # If text cannot be retrieved, use byte content
                    response_text = response.content.decode('utf-8', errors='replace')

                # Get actual request headers (including auto-added headers like content-length)
                request_headers = dict(response.request.headers) if hasattr(response, 'request') and response.request else dict(request_kwargs.get('headers', {}))

                # Build response data
                result = {
                    'code': 0,
                    'message': 'success',
                    'data': {
                        'url': url,
                        'status_code': response.status_code,
                        'response': response_text,
                        'request_headers': request_headers,
                        'response_headers': dict(response.headers),
                        'method': method
                    }
                }

                logger.info(f'HTTP request completed: {method} {url} -> {response.status_code}')
                return result

        except httpx.TimeoutException:
            logger.warning(f'HTTP request timeout ({timeout}s): {method} {url}')
            return {
                'code': 6,
                'message': f'Request timeout (exceeded {timeout} seconds)',
                'data': {'url': url, 'method': method}
            }
        except httpx.ConnectError as ex:
            logger.warning(f'HTTP connection error: {method} {url} - {ex!r}')
            return {
                'code': 7,
                'message': f'Connection failed: {ex!r}',
                'data': {'url': url, 'method': method}
            }
        except httpx.HTTPError as ex:
            logger.warning(f'HTTP error: {method} {url} - {ex!r}')
            return {
                'code': 8,
                'message': f'HTTP request error: {ex!r}',
                'data': {'url': url, 'method': method}
            }
        except Exception as ex:
            logger.error(f'Unexpected error in HTTP request: {method} {url} - {ex!r}')
            return {
                'code': 9,
                'message': f'Request failed: {ex!r}',
                'data': {'url': url, 'method': method}
            }

    except Exception as ex:
        logger.error(f'HTTP request API error: {ex!r}')
        raise HTTPException(status_code=500, detail=f'HTTP request API error: {ex!r}')

# ======================= Config Management =======================
import yaml
CONFIG_FILE = 'config.yaml'

def _load_config() -> models.AppConfig:
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                data = yaml.safe_load(f) or {}
                return models.AppConfig(**data)
        except Exception as e:
            logger.error(f'Failed to load config: {e}')
    return models.AppConfig()

@router.get('/api/config', response_model=models.ResponseModel)
async def get_config():
    """Get global backend configuration"""
    config = _load_config()
    return {'code': 0, 'message': 'success', 'data': config.dict()}

@router.post('/api/config', response_model=models.ResponseModel)
async def update_config(config_data: models.AppConfig):
    """Update global backend configuration"""
    try:
        with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
            yaml.dump(config_data.dict(), f, allow_unicode=True)
        return {'code': 0, 'message': 'success', 'data': config_data.dict()}
    except Exception as e:
        logger.error(f'Failed to save config: {e}')
        return {'code': 1, 'message': str(e), 'data': None}

# ======================= Session Management =======================
SESSIONS_DIR = 'sessions'
if not os.path.exists(SESSIONS_DIR):
    os.makedirs(SESSIONS_DIR)

@router.get('/api/sessions', response_model=models.ResponseModel)
async def list_sessions():
    """List all saved chat sessions"""
    sessions = []
    try:
        if os.path.exists(SESSIONS_DIR):
            files = [f for f in os.listdir(SESSIONS_DIR) if f.endswith('.json')]
            # sort by modification time descending
            files.sort(key=lambda x: os.path.getmtime(os.path.join(SESSIONS_DIR, x)), reverse=True)
            for file in files:
                try:
                    with open(os.path.join(SESSIONS_DIR, file), 'r', encoding='utf-8') as f:
                        data = json.load(f)
                        messages = data.get('messages', [])
                        create_time = None
                        for msg in messages:
                            if msg.get('role') == 'user' and msg.get('time'):
                                create_time = msg.get('time')
                                break

                        sessions.append({
                            'id': file.replace('.json', ''),
                            'title': data.get('title', 'New Chat'),
                            'config_name': data.get('config_name'),
                            'create_time': create_time,
                            'update_time': os.path.getmtime(os.path.join(SESSIONS_DIR, file))
                        })
                except Exception as e:
                    logger.warning(f'Failed to parse session file {file}: {e}')
                    pass
        return {'code': 0, 'message': 'success', 'data': sessions}
    except Exception as e:
        logger.error(f'Failed to list sessions: {e}')
        return {'code': 1, 'message': str(e), 'data': []}

@router.get('/api/sessions/{session_id}', response_model=models.ResponseModel)
async def get_session(session_id: str):
    """Get full chat history of a session"""
    session_file = os.path.join(SESSIONS_DIR, f'{session_id}.json')
    if os.path.exists(session_file):
        try:
            with open(session_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                return {'code': 0, 'message': 'success', 'data': data}
        except Exception as e:
            logger.error(f'Failed to read session {session_id}: {e}')
            return {'code': 1, 'message': str(e), 'data': None}
    logger.warning(f'Session not found: {session_id}')
    return {'code': 404, 'message': 'Session not found', 'data': None}

@router.post('/api/sessions/{session_id}', response_model=models.ResponseModel)
async def save_session(session_id: str, data: dict = Body(...)):
    """Save or update chat history for a session"""
    session_file = os.path.join(SESSIONS_DIR, f'{session_id}.json')
    try:
        with open(session_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return {'code': 0, 'message': 'success', 'data': session_id}
    except Exception as e:
        logger.error(f'Failed to save session {session_id}: {e}')
        return {'code': 1, 'message': str(e), 'data': None}

@router.delete('/api/sessions/{session_id}', response_model=models.ResponseModel)
async def delete_session(session_id: str):
    """Delete a session entirely"""
    session_file = os.path.join(SESSIONS_DIR, f'{session_id}.json')
    if os.path.exists(session_file):
        try:
            os.remove(session_file)
            return {'code': 0, 'message': 'success', 'data': session_id}
        except Exception as e:
            logger.error(f'Failed to delete session {session_id}: {e}')
            return {'code': 1, 'message': str(e), 'data': None}
    logger.warning(f'Session not found for delete: {session_id}')
    return {'code': 404, 'message': 'Session not found', 'data': None}

@router.delete('/api/sessions', response_model=models.ResponseModel)
async def clear_all_sessions():
    """Clear all sessions"""
    try:
        if os.path.exists(SESSIONS_DIR):
            for file in os.listdir(SESSIONS_DIR):
                if file.endswith('.json'):
                    os.remove(os.path.join(SESSIONS_DIR, file))
        return {'code': 0, 'message': 'success', 'data': None}
    except Exception as e:
        logger.error(f'Failed to clear sessions: {e}')
        return {'code': 1, 'message': str(e), 'data': None}

# ======================= Chat Completion API =======================
import asyncio

@router.post('/api/chat/completions')
async def chat_completions(req: dict = Body(...), request: Request = None):
    """Proxy chat requests to the local LLM based on config.yaml"""
    config = _load_config()

    # Allow frontend request to override backend global config
    base_url = req.get("base_url") or config.base_url
    api_key = req.get("api_key") or config.api_key
    model_name = req.get("model_name") or config.model_name
    system_prompt = req.get("system_prompt")
    if system_prompt is None:
        system_prompt = config.system_prompt
    extra_params = req.get("extra_params")
    if extra_params is None:
        extra_params = config.extra_params

    base_url = base_url.rstrip('/')
    if not base_url:
        raise HTTPException(status_code=400, detail="Base URL is not configured")

    url = f"{base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    messages = req.get("messages", [])
    if system_prompt and isinstance(system_prompt, str) and system_prompt.strip():
        # Inject system prompt if it's not already the first message
        if not messages or messages[0].get("role") != "system":
            messages.insert(0, {"role": "system", "content": system_prompt})

    payload = {
        "model": model_name,
        "messages": messages,
        "stream": req.get("stream", False),
    }

    if extra_params and isinstance(extra_params, dict):
        for k, v in extra_params.items():
            if k not in payload:
                payload[k] = v

    for k in ["temperature", "top_p", "max_tokens", "presence_penalty", "frequency_penalty"]:
        if k in req:
            payload[k] = req[k]

    stream = payload["stream"]

    try:
        if not stream:
            async with httpx.AsyncClient() as client:
                start_time = time.time()
                resp = await client.post(url, headers=headers, json=payload, timeout=300.0)
                resp.raise_for_status()
                data = resp.json()
                end_time = time.time()

                if "usage" in data:
                    data["usage"]["total_time"] = end_time - start_time

                return data
        else:
            async def generate():
                async with httpx.AsyncClient() as client:
                    start_time = time.time()
                    first_token_time = None
                    total_chars = 0
                    try:
                        # timeout config
                        async with client.stream("POST", url, headers=headers, json=payload, timeout=300.0) as resp:
                            if resp.status_code != 200:
                                error_text = await resp.aread()
                                error_msg = error_text.decode('utf-8', errors='ignore')
                                logger.error(f"Upstream API error ({resp.status_code}): {error_msg}")
                                yield f"data: {json.dumps({'error': f'Upstream API error {resp.status_code}: {error_msg}'})}\n\n"
                                return

                            async for chunk in resp.aiter_lines():
                                if chunk.startswith("data: "):
                                    chunk_data = chunk[6:]
                                    if chunk_data == "[DONE]":
                                        yield chunk + "\n\n"
                                        break

                                    try:
                                        parsed = json.loads(chunk_data)
                                        choices = parsed.get("choices", [])
                                        if choices and "delta" in choices[0]:
                                            delta = choices[0]["delta"]
                                            content = delta.get("content", "")
                                            if content:
                                                if first_token_time is None:
                                                    first_token_time = time.time()
                                                total_chars += len(content)

                                        yield chunk + "\n\n"

                                        # Minimum refresh interval logic.
                                        # Yielding slightly throttled to allow frontend UI to stay responsive
                                        await asyncio.sleep(0.01)
                                    except json.JSONDecodeError:
                                        yield chunk + "\n\n"
                                else:
                                    if chunk.strip():
                                        yield chunk + "\n\n"

                            end_time = time.time()
                            ttft = (first_token_time - start_time) if first_token_time else 0
                            total_time = end_time - start_time
                            telemetry = {
                                "ttft": ttft,
                                "total_time": total_time,
                                "total_chars": total_chars
                            }
                            yield f"data: [TELEMETRY] {json.dumps(telemetry)}\n\n"
                    except Exception as e:
                        logger.error(f"Streaming error: {e}")
                        yield f"data: {json.dumps({'error': str(e)})}\n\n"

            return StreamingResponse(generate(), media_type="text/event-stream")

    except Exception as e:
        logger.error(f"Chat completion error: {e}")
        raise HTTPException(status_code=500, detail=str(e))



